name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: CI Placeholder
        run: echo "CI pipeline will be added later."